### ISSUE TITLE
epm4.1 doen't compile on Intel iMac with Mac OS X 10.5 (Leopard)

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/epm#11]
Version: 4.1
Original reporter: 

My attempt to build epm4.1 on Intel iMac with Mac OS X 10.5 (Leopard) produced the following error message:

.....
Compiling gui-common.cxx...
Linking setup...
ld: warning in /usr/local/lib/libfltk_images.a, file is not of required architecture
ld: warning in /usr/local/lib/libfltk_png.a, file is not of required architecture
ld: warning in /usr/local/lib/libfltk_jpeg.a, file is not of required architecture
ld: warning in /usr/local/lib/libfltk.a, file is not of required architecture
Undefined symbols for architecture ppc:
  "Fl_Round_Button::Fl_Round_Button(int, int, int, int, char const*)", referenced from:
      make_window()     in setup.o
.....
ld: symbol(s) not found for architecture ppc
collect2: ld returned 1 exit status
lipo: can't open input file: /var/tmp//ccgyXgvI.out (No such file or directory)
make: *** [setup] Error 1
